version: "2"
services:
  app:
    container_name: ambev-api
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    depends_on:
      - redis
    ports:
      - "4001:4001"
    volumes:
      - .:/usr/src/app
    command: nodemon server.js
  redis:
    image: redis:4.0-alpine
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"